/**
 * @file CAN_DB.h
 *
 * @brief This header file was generated by cantools version 0.1.dev1945+g0176440c4 Fri Jun 26 15:27:48 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CAN_DB_H
#define CAN_DB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define DASHBOARD_CONTROL_FRAME_ID (0x3e1u)
#define DASHBOARD_WIPERS_FRAME_ID (0x3e3u)
#define DASHBOARD_NODE_FRAME_ID (0x3e0u)
#define DASHBOARD_END_FRAME_ID (0x3ffu)
#define DASHBOARD_LIGHTS_FRAME_ID (0x3e2u)
#define DASHBOARD_CC_FRAME_ID (0x3e4u)

/* Frame lengths in bytes. */
#define DASHBOARD_CONTROL_LENGTH (8u)
#define DASHBOARD_WIPERS_LENGTH (1u)
#define DASHBOARD_NODE_LENGTH (8u)
#define DASHBOARD_END_LENGTH (8u)
#define DASHBOARD_LIGHTS_LENGTH (1u)
#define DASHBOARD_CC_LENGTH (8u)

/* Extended or standard frame types. */
#define DASHBOARD_CONTROL_IS_EXTENDED (0)
#define DASHBOARD_WIPERS_IS_EXTENDED (0)
#define DASHBOARD_NODE_IS_EXTENDED (0)
#define DASHBOARD_END_IS_EXTENDED (0)
#define DASHBOARD_LIGHTS_IS_EXTENDED (0)
#define DASHBOARD_CC_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define DASHBOARD_CONTROL_CYCLE_TIME_MS (100u)
#define DASHBOARD_NODE_CYCLE_TIME_MS (1000u)
#define DASHBOARD_END_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define DASHBOARD_WIPERS_STATUS_OFF_CHOICE (0u)
#define DASHBOARD_WIPERS_STATUS_ONCE_CHOICE (1u)
#define DASHBOARD_WIPERS_STATUS_INTERVAL_CHOICE (2u)
#define DASHBOARD_WIPERS_STATUS_LOW_CHOICE (3u)
#define DASHBOARD_WIPERS_STATUS_HIGH_CHOICE (4u)
#define DASHBOARD_WIPERS_STATUS_BACK_CHOICE (5u)
#define DASHBOARD_WIPERS_STATUS_BACK_FLUID_CHOICE (6u)
#define DASHBOARD_WIPERS_STATUS_FLUID_CHOICE (7u)

#define DASHBOARD_LIGHTS_HEADLIGHTS_OFF_CHOICE (0u)
#define DASHBOARD_LIGHTS_HEADLIGHTS_AUTO_CHOICE (1u)
#define DASHBOARD_LIGHTS_HEADLIGHTS_DAY_CHOICE (2u)
#define DASHBOARD_LIGHTS_HEADLIGHTS_NIGHT_CHOICE (3u)
#define DASHBOARD_LIGHTS_HEADLIGHTS_HIGHBEAMS_CHOICE (4u)

#define DASHBOARD_LIGHTS_TURNSIGNAL_LEFT_OFF_CHOICE (0u)
#define DASHBOARD_LIGHTS_TURNSIGNAL_LEFT_ONCE_CHOICE (1u)
#define DASHBOARD_LIGHTS_TURNSIGNAL_LEFT_ON_CHOICE (2u)

#define DASHBOARD_LIGHTS_TURNSIGNAL_RIGHT_OFF_CHOICE (0u)
#define DASHBOARD_LIGHTS_TURNSIGNAL_RIGHT_ONCE_CHOICE (1u)
#define DASHBOARD_LIGHTS_TURNSIGNAL_RIGHT_ON_CHOICE (2u)

#define DASHBOARD_LIGHTS_EMERGENCY_OFF_CHOICE (0u)
#define DASHBOARD_LIGHTS_EMERGENCY_ON_CHOICE (1u)

/* Frame Names. */
#define DASHBOARD_CONTROL_NAME "Dashboard_Control"
#define DASHBOARD_WIPERS_NAME "Dashboard_Wipers"
#define DASHBOARD_NODE_NAME "Dashboard_NODE"
#define DASHBOARD_END_NAME "Dashboard_END"
#define DASHBOARD_LIGHTS_NAME "Dashboard_Lights"
#define DASHBOARD_CC_NAME "Dashboard_CC"

/* Signal Names. */
#define DASHBOARD_CONTROL_ABSOLUTE_ENCODER_NAME "Absolute_Encoder"
#define DASHBOARD_CONTROL_PRND_NAME "PRND"
#define DASHBOARD_WIPERS_STATUS_NAME "Status"
#define DASHBOARD_NODE_ERROR_CODE_NAME "Error_Code"
#define DASHBOARD_NODE_RESERVED_NAME "Reserved"
#define DASHBOARD_NODE_SEVERITY_NAME "Severity"
#define DASHBOARD_NODE_NODE_EXECUTION_HALTED_NAME "Node_Execution_Halted"
#define DASHBOARD_NODE_ERROR_SPECIFIC_DATA_NAME "Error_Specific_Data"
#define DASHBOARD_LIGHTS_HEADLIGHTS_NAME "Headlights"
#define DASHBOARD_LIGHTS_TURNSIGNAL_LEFT_NAME "TurnSignal_Left"
#define DASHBOARD_LIGHTS_TURNSIGNAL_RIGHT_NAME "TurnSignal_Right"
#define DASHBOARD_LIGHTS_EMERGENCY_NAME "Emergency"

/**
 * Signals in message Dashboard_Control.
 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_Control_t {
    /**
     * Validity flag for absolute encoder signal indicating whether the steering position data is correct and usable.
     *
     * Range: -16384..0 (-540..540 deg)
     * Scale: 0.06591796875
     * Offset: 540
     */
    uint16_t Absolute_Encoder;

    /**
     * Gear selector position derived from ADC reading of PRND switch (4 discrete positions).
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t PRND;
};

/**
 * Signals in message Dashboard_Wipers.
 *
 * Sent on event (change)
 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_Wipers_t {
    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t Status;
};

/**
 * Signals in message Dashboard_NODE.
 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_NODE_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t Error_Code;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Reserved;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Severity;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t Node_Execution_Halted;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint64_t Error_Specific_Data;
};

/**
 * Signals in message Dashboard_END.
 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_END_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Signals in message Dashboard_Lights.
 *
 * Sent on event (change)

 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_Lights_t {
    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t Headlights;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t TurnSignal_Left;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t TurnSignal_Right;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t Emergency;
};

/**
 * Signals in message Dashboard_CC.
 *
 * Sent on event (change)
 *
 * All signal values are as on the CAN bus.
 */
struct Dashboard_CC_t {
    /**
     * Dummy signal in empty message.
     */
    uint8_t dummy;
};

/**
 * Pack message Dashboard_Control.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_Control_pack(
    uint8_t *dst_p,
    const struct Dashboard_Control_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_Control.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_Control_init(struct Dashboard_Control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t Dashboard_Control_Absolute_Encoder_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Control_Absolute_Encoder_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Control_PRND_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Control_PRND_is_in_range(uint8_t value);

/**
 * Pack message Dashboard_Wipers.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_Wipers_pack(
    uint8_t *dst_p,
    const struct Dashboard_Wipers_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_Wipers.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_Wipers_init(struct Dashboard_Wipers_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Wipers_Status_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Wipers_Status_is_in_range(uint8_t value);

/**
 * Pack message Dashboard_NODE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_NODE_pack(
    uint8_t *dst_p,
    const struct Dashboard_NODE_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_NODE.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_NODE_init(struct Dashboard_NODE_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t Dashboard_NODE_Error_Code_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_NODE_Error_Code_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_NODE_Reserved_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_NODE_Reserved_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_NODE_Severity_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_NODE_Severity_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_NODE_Node_Execution_Halted_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_NODE_Node_Execution_Halted_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t Dashboard_NODE_Error_Specific_Data_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_NODE_Error_Specific_Data_is_in_range(uint64_t value);

/**
 * Pack message Dashboard_END.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_END_pack(
    uint8_t *dst_p,
    const struct Dashboard_END_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_END.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_END_init(struct Dashboard_END_t *msg_p);

/**
 * Pack message Dashboard_Lights.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_Lights_pack(
    uint8_t *dst_p,
    const struct Dashboard_Lights_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_Lights.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_Lights_init(struct Dashboard_Lights_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Lights_Headlights_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Lights_Headlights_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Lights_TurnSignal_Left_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Lights_TurnSignal_Left_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Lights_TurnSignal_Right_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Lights_TurnSignal_Right_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t Dashboard_Lights_Emergency_encode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool Dashboard_Lights_Emergency_is_in_range(uint8_t value);

/**
 * Pack message Dashboard_CC.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int Dashboard_CC_pack(
    uint8_t *dst_p,
    const struct Dashboard_CC_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Dashboard_CC.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int Dashboard_CC_init(struct Dashboard_CC_t *msg_p);


#ifdef __cplusplus
}
#endif

#endif
