/**
 * @file CAN_DB.c
 *
 * @brief This source file was generated by cantools version 0.1.dev1945+g0176440c4 Fri Sep  4 20:56:38 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "CAN_DB.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int Pedals_END_pack(
    uint8_t *dst_p,
    const struct Pedals_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int Pedals_END_unpack(
    struct Pedals_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingBack_END_pack(
    uint8_t *dst_p,
    const struct CoolingBack_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingBack_END_unpack(
    struct CoolingBack_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingLeft_END_pack(
    uint8_t *dst_p,
    const struct CoolingLeft_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingLeft_END_unpack(
    struct CoolingLeft_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingMotor_END_pack(
    uint8_t *dst_p,
    const struct CoolingMotor_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingMotor_END_unpack(
    struct CoolingMotor_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingRight_END_pack(
    uint8_t *dst_p,
    const struct CoolingRight_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int CoolingRight_END_unpack(
    struct CoolingRight_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int EngineLeft_STATIC_TPDO1_unpack(
    struct EngineLeft_STATIC_TPDO1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t LeftMotorCurrent;
    uint16_t LeftMotorRPM;
    uint16_t LeftMotorTorque;

    if (size < 8u) {
        return (-EINVAL);
    }

    LeftMotorRPM = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    LeftMotorRPM |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->LeftMotorRPM = (int16_t)LeftMotorRPM;
    LeftMotorCurrent = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    LeftMotorCurrent |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->LeftMotorCurrent = (int16_t)LeftMotorCurrent;
    dst_p->LeftMotorVoltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->LeftMotorVoltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    LeftMotorTorque = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    LeftMotorTorque |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->LeftMotorTorque = (int16_t)LeftMotorTorque;

    return (0);
}

int EngineLeft_STATIC_TPDO1_init(struct EngineLeft_STATIC_TPDO1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct EngineLeft_STATIC_TPDO1_t));

    return 0;
}

double EngineLeft_STATIC_TPDO1_LeftMotorRPM_decode(int16_t value)
{
    return ((double)value);
}

bool EngineLeft_STATIC_TPDO1_LeftMotorRPM_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

double EngineLeft_STATIC_TPDO1_LeftMotorCurrent_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool EngineLeft_STATIC_TPDO1_LeftMotorCurrent_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

double EngineLeft_STATIC_TPDO1_LeftMotorVoltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool EngineLeft_STATIC_TPDO1_LeftMotorVoltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

double EngineLeft_STATIC_TPDO1_LeftMotorTorque_decode(int16_t value)
{
    return ((double)value);
}

bool EngineLeft_STATIC_TPDO1_LeftMotorTorque_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

int EngineRight_STATIC_TPDO1_unpack(
    struct EngineRight_STATIC_TPDO1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t RightMotorCurrent;
    uint16_t RightMotorRPM;
    uint16_t RightMotorTorque;

    if (size < 8u) {
        return (-EINVAL);
    }

    RightMotorRPM = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    RightMotorRPM |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->RightMotorRPM = (int16_t)RightMotorRPM;
    RightMotorCurrent = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    RightMotorCurrent |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->RightMotorCurrent = (int16_t)RightMotorCurrent;
    dst_p->RightMotorVoltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->RightMotorVoltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    RightMotorTorque = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    RightMotorTorque |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->RightMotorTorque = (int16_t)RightMotorTorque;

    return (0);
}

int EngineRight_STATIC_TPDO1_init(struct EngineRight_STATIC_TPDO1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct EngineRight_STATIC_TPDO1_t));

    return 0;
}

double EngineRight_STATIC_TPDO1_RightMotorRPM_decode(int16_t value)
{
    return ((double)value);
}

bool EngineRight_STATIC_TPDO1_RightMotorRPM_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

double EngineRight_STATIC_TPDO1_RightMotorCurrent_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool EngineRight_STATIC_TPDO1_RightMotorCurrent_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

double EngineRight_STATIC_TPDO1_RightMotorVoltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool EngineRight_STATIC_TPDO1_RightMotorVoltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

double EngineRight_STATIC_TPDO1_RightMotorTorque_decode(int16_t value)
{
    return ((double)value);
}

bool EngineRight_STATIC_TPDO1_RightMotorTorque_is_in_range(int16_t value)
{
    return ((value >= -500) && (value <= 500));
}

int Dashboard_Control_pack(
    uint8_t *dst_p,
    const struct Dashboard_Control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Absolute_Encoder, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Absolute_Encoder, 8u, 0x3fu);
    dst_p[1] |= pack_left_shift_u8(src_p->PRND, 6u, 0xc0u);
    dst_p[2] |= pack_left_shift_u8(src_p->Mode, 0u, 0x01u);

    return (8);
}

int Dashboard_Control_init(struct Dashboard_Control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct Dashboard_Control_t));

    return 0;
}

uint16_t Dashboard_Control_Absolute_Encoder_encode(double value)
{
    return (uint16_t)((value - 540.0) / 0.06591796875);
}

bool Dashboard_Control_Absolute_Encoder_is_in_range(uint16_t value)
{
    return (value <= 0u);
}

uint8_t Dashboard_Control_PRND_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Control_PRND_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t Dashboard_Control_Mode_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Control_Mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int Dashboard_Wipers_pack(
    uint8_t *dst_p,
    const struct Dashboard_Wipers_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->Status, 0u, 0x07u);

    return (1);
}

int Dashboard_Wipers_init(struct Dashboard_Wipers_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct Dashboard_Wipers_t));

    return 0;
}

uint8_t Dashboard_Wipers_Status_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Wipers_Status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int Dashboard_NODE_pack(
    uint8_t *dst_p,
    const struct Dashboard_NODE_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->Error_Code, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->Error_Code, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->Reserved, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->Severity, 4u, 0x70u);
    dst_p[2] |= pack_left_shift_u8(src_p->Node_Execution_Halted, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u64(src_p->Error_Specific_Data, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->Error_Specific_Data, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->Error_Specific_Data, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->Error_Specific_Data, 24u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->Error_Specific_Data, 32u, 0xffu);

    return (8);
}

int Dashboard_NODE_init(struct Dashboard_NODE_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct Dashboard_NODE_t));

    return 0;
}

uint16_t Dashboard_NODE_Error_Code_encode(double value)
{
    return (uint16_t)(value);
}

bool Dashboard_NODE_Error_Code_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t Dashboard_NODE_Reserved_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_NODE_Reserved_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t Dashboard_NODE_Severity_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_NODE_Severity_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t Dashboard_NODE_Node_Execution_Halted_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_NODE_Node_Execution_Halted_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint64_t Dashboard_NODE_Error_Specific_Data_encode(double value)
{
    return (uint64_t)(value);
}

bool Dashboard_NODE_Error_Specific_Data_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

int Dashboard_END_pack(
    uint8_t *dst_p,
    const struct Dashboard_END_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int Dashboard_END_unpack(
    struct Dashboard_END_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int Dashboard_Lights_pack(
    uint8_t *dst_p,
    const struct Dashboard_Lights_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->Headlights, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->TurnSignal_Left, 3u, 0x18u);
    dst_p[0] |= pack_left_shift_u8(src_p->TurnSignal_Right, 5u, 0x60u);
    dst_p[0] |= pack_left_shift_u8(src_p->Emergency, 7u, 0x80u);

    return (1);
}

int Dashboard_Lights_init(struct Dashboard_Lights_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct Dashboard_Lights_t));

    return 0;
}

uint8_t Dashboard_Lights_Headlights_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Lights_Headlights_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t Dashboard_Lights_TurnSignal_Left_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Lights_TurnSignal_Left_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t Dashboard_Lights_TurnSignal_Right_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Lights_TurnSignal_Right_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t Dashboard_Lights_Emergency_encode(double value)
{
    return (uint8_t)(value);
}

bool Dashboard_Lights_Emergency_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int Dashboard_CC_pack(
    uint8_t *dst_p,
    const struct Dashboard_CC_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}

int Dashboard_CC_unpack(
    struct Dashboard_CC_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;
    (void)size;

    return (0);
}
